micronaut:
  application:
    name: livecode140926
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  producers:
    default:
      acks: all
      enable.idempotence: true
